#!/bin/bash


# Install Packages
system_type=$(uname -s)
if [ "$system_type" = "Darwin" ]; then
    bin/macsetup.sh
else
    ~/bin/1-packages.sh
    ~/bin/2-neovim.sh
    sudo ~/bin/3-sudo-go.sh
fi
mkdir -p $HOME/setup
cd $HOME/setup
git clone https://github.com/iridakos/goto.git
cd goto
sudo ./install

# Bootstrap Neovim

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping neovim"
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi


sudo pip install doitlive
sudo pip install jrnl

#reload to get go settings
source ~/.bashrc

# Install a few essential Go apps
go get -u github.com/direnv/direnv
go get -u github.com/justjanne/powerline-go
go get -u github.com/erroneousboat/slack-term

# goto.sh
mkdir -p ~/setup
cd setup
git clone https://github.com/iridakos/goto.git
cd goto
sudo ./install
cd



# install nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash


